services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - ${DATA_PATH}/db_data:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    networks:
      - transcendence-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: node-backend
    environment:
      NODE_ENV: production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    secrets:
      - POSTGRES_PASSWORD
    networks:
      - transcendence-network
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      DOMAIN_NAME: ${DOMAIN}
    depends_on:
      - backend
    networks:
      - transcendence-network
    volumes:
      - ../secrets/certs:/etc/ssl/private/
    ports:
      - "5173:5173"
      

volumes:
  db_data:
    external: true
  site_data:
    external: true

networks:
  transcendence-network:
    driver: bridge

secrets:
  POSTGRES_PASSWORD:
    file: ../secrets/POSTGRES_PASSWORD.txt
